using System;
using System.Collections.Generic;
using System.Text;
using System.Diagnostics;

namespace ConsoleAppTest.DebugAndSecurity
{
    // You can also use information generated by logging and tracing to investigate performance issues with systems out in the field.If is very useful to be able to
    // determine the loading levels and the nature of transactions being performed on the customer site.
    // You use logging to find out what your program is doing and what happened    when it failed.You use tracing to discover the path followed by the program to
    // perform a particular action.    public class Diagnostics
    {
        // The System.Diagnostics namespace contains Debug and Trace classes that can
        // be used to trace execution of a program.The classes contain methods that can be used to generate tracing output from a program when it runs.
        public void DebugCodeTracing()
        {

        }

        // 
        public void TraceCodeTracing()
        {

        }

        // 
        public void AssertionsInDebug()
        {

        }

        // 
        public void TraceListener()
        {

        }

        // 
        public void SimpleTraceSource()
        {

        }

        // 
        public void TracesWitch()
        {

        }

        // 
        public void SourceSwitch()
        {

        }

        // 
        public void ConfigFile()
        {

        }

        // 
        public void StopwatchClass()
        {

        }

        // 
        public void ReadPerformanceCounters()
        {

        }

        // 
        public void CreatePerformanceCounters()
        {

        }

        // 
        public void WriteToTheEventLog()
        {

        }

        // 
        public void ReadFromTheEventLog()
        {

        }

        // 
        public void BindToTheEventLog()
        {

        }
    }
}
