using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MusicTracks.Models
{
    public class MusicTrack
    {
        public MusicTrack()
        {
        }

        // Copy constructor for MusicTrack
        public MusicTrack(MusicTrack source)
        {
            Artist = source.Artist;
            Title = source.Title;
            Length = source.Length;
        }
        // If you want to be sure that a method can’t change the contents of an object that it is given a reference to, you will have to copy the object
        // and pass the method a reference to the copy. You can make it easy to do this by create a method called a copy constructor for the MusicTrack class.	

        public MusicTrack(string artist, string title, int length)
        {
            Artist = artist;
            Title = title;
            Length = length;
        }

        public int ID { get; set; }
        public string Artist { get; set; }
        public string Title { get; set; }

        // The ASP.NET application has some validation behaviors. The track length property has been declared as an integer type, and the user interface that 
        // was generated by the scaffolding process contains validation that prevents the user from entering a track length that is not a number. However, we can 
        // improve the validation of the data by adding attributes to the model class
        [Range(20, 600)]
        public int Length { get; set; }
    }
}
